project:
  type: website

website:
  favicon: "./slideshows/logos/kg-logo.svg"
  navbar:
    title: "Quarto"
    logo: "./slideshows/logos/kg-logo.svg"
    left:
      - href: index.qmd
        text: Home
      - text: YouTube Tutorials
        menu: 
          - text: "Quarto Crash Course"
            href: "https://youtu.be/_VKxTPWDhA4?si=plDlvlMh0bRuQZPG"
            target: _blank
          - text: "Generate 100s of Custom Reports in Minutes"
            href: "https://youtu.be/_kjs_u3Ctt4?si=i6IgBavZeJfuHyvR"
          - text: "Fastest Way to Convert Jupyter Notebooks into Analytics Reports"
            href: "https://youtu.be/TS0w-tSH3Jc?si=3t5PvqLpS003yyjB"
          - text: "Real-world Python Dashboard Project"
            href: "https://youtu.be/gCLCn4TVlWo?si=i8_FDCKwf9s6Nj2m"
          - text: "Create Slideshows with Markdown & Python Code!"
            href: "https://youtu.be/kWnMc0GwX-U?si=oG6atMGifPJgnM8h"
    tools:
      - icon: "github"
        href: "https://github.com/KeithGalli/quarto-portfolio"
      - icon: "youtube"
        href: "https://www.youtube.com/@keithgalli"
      - icon: "linkedin"
        href: "https://www.linkedin.com/in/keithgalli/"
  sidebar:
    style: "docked"
    border: false
    collapse-level: 1
    search: true
    contents:
      - text: "Posit Quarto Series (Python)"
        align: "right"
        alignment: "right"
        href: index.qmd
      - '---'
      - section: "Quarto Crash Course"
        collapsed: true
        contents: quarto-crash-course/*
      - section: " # Data Visualization"
        href: index.qmd
        contents:
          - section: "Hello there"
            contents:
          - section: "YHo"
            contents:
              - test.qmd

  page-footer:
    left: "© 2025, Keith Galli"
    right:
      - icon: "github"
        href: "https://github.com/KeithGalli/quarto-portfolio"
      - icon: "youtube"
        href: "https://www.youtube.com/@keithgalli"
      - icon: "linkedin"
        href: "https://www.linkedin.com/in/keithgalli/"


format:
  html:
    theme: solar
